# prometheus.yml
global:
  scrape_interval: 1s
  external_labels:
    monitor: 'monitor'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'data-service'
    static_configs:
      - targets: ['localhost:8083']
