version: '3.1'

services:
  device-db:
    image: postgres
    ports:
      - "${DB_PORT}:${DB_PORT}"
    restart: ${DB_RESTART_TYPE}
    env_file:
      - .env
    environment:
      POSTGRES_URL: ${DB_URL}
      POSTGRES_PORT: ${DB_PORT}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - ./data:/var/lib/${DB_NAME}
    command: -p ${DB_PORT}

  device-service:
    image: quarkus/device-service-fast-jar
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile.fast-jar
    ports:
      - "${APP_PORT}:${APP_PORT}"
    env_file:
      - .env
    depends_on:
      - device-db
