{
 "title": "Device Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "2s",
 "panels": [
  {
   "title": "Data count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "application_device_serial687837771_dataCount_total"
    }
   ]
  },
  {
   "title": "Description",
   "type": "text",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 0 },
   "content": "\n# Device with serial No. 687837771\n\n#### Metrics for street lights\n\n\n\n\n"
  },
  {
   "title": "Detect movement",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "none", "label": "Detect movement" }
   ],
   "targets": [
    {
     "expr": "application_device_serial687837771_detect",
     "legendFormat": "Detect"
    }
   ]
  },
  {
   "title": "Emitted intensity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "percent", "label": "Intensity" }
   ],
   "targets": [
    {
     "expr": "application_device_serial687837771_intensity",
     "legendFormat": "intensity"
    }
   ]
  },
  {
   "title": "Ambient light",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "lumens" }
   ],
   "targets": [
    {
     "expr": "application_device_serial687837771_ambient",
     "legendFormat": "Ambient"
    }
   ]
  }
 ]
}